apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
      - name: rag-api
        image: image-registry.openshift-image-registry.svc:5000/openshift-terminal/rag-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: sha256~kiAMUFsc1GGx0Qc8IzBLTuDWHEcIGQRbQnlW5JIBVJ0
          valueFrom:
            secretKeyRef:
              name: openshift-ai-api-key
              key: api-key
